apiVersion: apps/v1
kind: Deployment
metadata:
  name: disallowed-redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 6
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis
